### PR TITLE
stacktrace: Use `mallinfo2()` instead of `mallinfo()`

### PR DESCRIPTION
**Pull request by Bojun-Seo**
`mallinfo()` function is deprecated function. So, use `mallinfo2()` function instead

### CODE REVIEW

**Comment by Bojun-Seo** [comment]
This patch will resolve this issue.
https://github.com/honggyukim/heaptrace/issues/8

**Comment by honggyukim** [comment]
Thanks for the patch. Could you add more description why `mallinfo` is deprecated and replaced by `mallinfo2` by the following commit since glibc-2.33?
https://github.com/bminor/glibc/commit/e3960d1c57e57f33e0e846d615788f4ede73b945

**Comment by Bojun-Seo** [comment]
Thanks for your good comment. I changed the commit message as you suggested.

**Comment by honggyukim** [comment]
It looks we need to check whether the current system has glibc-2 33 or later versions because `mallinfo2` isn't available in old glibc versions.

Please consider using such checks as follows.
```c
#include <stdio.h>

#if (__GLIBC__ > 2) || (__GLIBC__ == 2 && __GLIBC_MINOR__ >= 33)
#define GLIBC_233_OR_LATER
#endif

int main() {
#ifdef GLIBC_233_OR_LATER
    printf("glibc version is 2.33 or later\n");
#else
    printf("glibc version is lower than 2.33\n");
#endif
    return 0;
}
```

**Comment by Bojun-Seo** [comment]
Make sense. I added `GLIBC_233_OR_LATER` to decide which API to use.
I changed the code to use `mallinfo()` for old `glibc` versions and use `mallinfo2()` for others.

**Review by honggyukim — APPROVED** [review]
LGTM. Thanks a lot for fixing this!

**Comment by honggyukim** [comment]
> This patch will resolve this issue.
> https://github.com/honggyukim/heaptrace/issues/8

If so, please add `Fixed: #8` in the commit message later in the same case. It will automatically close the issue when this PR is merged.

**Pull request merged**
