### PR TITLE
Implement ignore

### PR DESCRIPTION
**Pull request by Bojun-Seo**
Sometimes user wants to remove some reports not necessary to be traced.
`Suppressions` feature will filter user defined symbols, functions and files.
This feature resembles `suppressions` feature in `llvm-project`

### CODE REVIEW

**Comment by honggyukim** [comment]
It'd be helpful if you write some execution sequence for the usage of this suppression feature in the commit message.

**Comment by Bojun-Seo** [comment]
I'll add the execution sequence for the usage of this suppression feature on commit message after #29 is merged.
Since this patch(#28) will conflict with #29

**Comment by honggyukim** [comment]
Thanks for the PR, but I think the name `suppressions` is better to be `ignore`.

**Comment by Bojun-Seo** [comment]
That sounds nice, I'll change the name from `suppressions` to `ignore`

**Comment by honggyukim** [comment]
I couldn't look into the details but just tested this PR. It looks working fine so I don't want to hold this PR.

I just want to ask you to give 2 whitespaces when pasting the console output.

Your current commit message is written as follows.
```
You can use ignore option as follows.
$ ./heaptrace --ignore=ignore.txt samples/factorial.out
```
But I think this is better to be written as follows.
```
You can use ignore option as follows.

  $ ./heaptrace --ignore=ignore.txt samples/factorial.out
```
And please rebase this PR onto the current main branch.

**Comment by Bojun-Seo** [comment]
I changed the patch as you suggested.
Thank you for the review!

**Review by honggyukim — APPROVED** [review]
I think it looks good so please test it again yourself and merge this into master.

**Pull request merged**
